"""empty message

Revision ID: 720dcc5226b5
Revises: 88b6bac28d8d
Create Date: 2025-12-28 13:07:12.941770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720dcc5226b5'
down_revision: Union[str, Sequence[str], None] = '88b6bac28d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('check_in', sa.Date(), nullable=False))
    op.add_column('booking', sa.Column('check_out', sa.Date(), nullable=False))
    op.alter_column('booking', 'created_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('review', 'created_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'created_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('booking', 'created_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('booking', 'check_out')
    op.drop_column('booking', 'check_in')
    # ### end Alembic commands ###
