"""empty message

Revision ID: 08285d208972
Revises: 26c80e28ceb7
Create Date: 2026-01-10 17:22:34.275222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08285d208972'
down_revision: Union[str, Sequence[str], None] = '26c80e28ceb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('post_content_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post', 'post', ['post_content_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'post_content_id')
    op.drop_table('post_content')
    # ### end Alembic commands ###
