"""empty message

Revision ID: 68f20d6781f1
Revises: d7258ffc60bf
Create Date: 2026-01-11 02:13:59.112473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f20d6781f1'
down_revision: Union[str, Sequence[str], None] = 'd7258ffc60bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('post_post_content_id_fkey'), 'post', type_='foreignkey')
    op.drop_column('post', 'post_content_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_content_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('post_post_content_id_fkey'), 'post', 'post', ['post_content_id'], ['id'])
    # ### end Alembic commands ###
