"""empty message

Revision ID: d1e548af73b2
Revises: 68f20d6781f1
Create Date: 2026-01-11 02:20:21.779769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e548af73b2'
down_revision: Union[str, Sequence[str], None] = '68f20d6781f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_content', sa.Column('post_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post_content', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_content', type_='foreignkey')
    op.drop_column('post_content', 'post_id')
    # ### end Alembic commands ###
