# Generated by Django 5.2.9 on 2026-01-26 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='district_name_en',
            field=models.CharField(max_length=54, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='district_name_ru',
            field=models.CharField(max_length=54, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='documents_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='documents_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='title_en',
            field=models.CharField(max_length=54, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='title_ru',
            field=models.CharField(max_length=54, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_en',
            field=models.CharField(max_length=54, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_ru',
            field=models.CharField(max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='region_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='house_app.region'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='house_app.city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='house_app.city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='region_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='house_app.region'),
        ),
        migrations.AlterField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='house_app.property'),
        ),
    ]
